global:
  resolve_timeout: 30s

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'notif-discord'
  routes:
    - match:
        severity: critical
      receiver: 'notif-discord-urgent'
      repeat_interval: 15m

receivers:
  - name: 'notif-discord'
    webhook_configs:
      - url: 'http://host.docker.internal:5000/alert'
        send_resolved: true
  - name: 'notif-discord-urgent'
    webhook_configs:
      - url: 'http://host.docker.internal:5000/alert'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['instance']
